// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG70ICwpL-u81oH0QWdz3fcMiDnLQdYN8',
    appId: '1:773637258020:android:d9a7fec22a2d4f0ec091b1',
    messagingSenderId: '773637258020',
    projectId: 'geocue-antigravity',
    storageBucket: 'geocue-antigravity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Z3GYUN05R7V1ZebN1ltFS7MpRVN2il8',
    appId: '1:773637258020:ios:d5b48228d0e39008c091b1',
    messagingSenderId: '773637258020',
    projectId: 'geocue-antigravity',
    storageBucket: 'geocue-antigravity.firebasestorage.app',
    iosBundleId: 'com.geocue.geocue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Z3GYUN05R7V1ZebN1ltFS7MpRVN2il8',
    appId: '1:773637258020:ios:d5b48228d0e39008c091b1',
    messagingSenderId: '773637258020',
    projectId: 'geocue-antigravity',
    storageBucket: 'geocue-antigravity.firebasestorage.app',
    iosBundleId: 'com.geocue.geocue',
  );
}
